name: Magic Chess Synergy Simulator

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hamidbae/mc-simulator:latest
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Starting deploy container"
      - uses: actions/checkout@v3
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZZURE_PUBLIC_IP }}
          port: 22
          username: ${{ secrets.AZZURE_USERNAME }}
          key: ${{ secrets.AZZURE_PRIVATE_KEY }}
          script: |
            docker stop op-comic-api
            docker rmi hamidbae/mc-simulator:latest
            docker pull hamidbae/mc-simulator:latest
            docker run -d --rm --name mc-simulator -p 80:8080 --env-file ./.env --network mc-network hamidbae/mc-simulator:latest